create table if not exists public.ref_payment_methods (
  id bigint generated by default as identity primary key,
  label text not null unique,
  method_type text not null check (method_type in ('cash', 'card', 'fop')),
  worker_name text null,
  requires_confirmation boolean not null default false,
  active boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ref_payment_methods_worker_required_for_non_cash
    check ((method_type = 'cash' and worker_name is null) or (method_type <> 'cash' and worker_name is not null))
);

create index if not exists ref_payment_methods_active_idx
  on public.ref_payment_methods (active);

create index if not exists ref_payment_methods_worker_idx
  on public.ref_payment_methods (worker_name);

create index if not exists ref_payment_methods_type_idx
  on public.ref_payment_methods (method_type);

-- Seed defaults matching legacy hardcoded methods.
-- CASH must be public and non-confirmable; CARD/FOP are confirmable and owned by one worker.
insert into public.ref_payment_methods (label, method_type, worker_name, requires_confirmation, active, sort_order)
values
  ('🪙 Наличка', 'cash', null, false, true, 10),
  ('👤 Шепель Александр 💳 4149 4975 1422 9980 (PRIVAT)', 'card', 'Sasha Manager', true, true, 20),
  ('👤 Киртока Максим 💳 4441 1144 6035 9811 (MONO)', 'card', 'Maksim', true, true, 30),
  ('👤 Киртока Анастасия 💳 4149 6090 2872 4237 (PRIVAT)', 'card', 'Maksim', true, true, 40),
  ('👤 Бабенко Олег 💳 5457 0825 0103 4743 (PRIVAT)', 'card', 'Oleg Starshiy', true, true, 50),
  ('📂 БЕЗНАЛ БАБЕНКО', 'fop', 'Oleg Starshiy', true, true, 60)
on conflict (label) do update set
  method_type = excluded.method_type,
  worker_name = excluded.worker_name,
  requires_confirmation = excluded.requires_confirmation,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();

