create table if not exists public.ref_warehouses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.ref_dropshippers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  worker_name text null,
  created_at timestamptz not null default now()
);
